import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const html = readFileSync(new URL("../public/index.html", import.meta.url), "utf8");
const server = readFileSync(new URL("../server.mjs", import.meta.url), "utf8");
const claudeProvider = readFileSync(new URL("../providers/claude.mjs", import.meta.url), "utf8");
const codexProvider = readFileSync(new URL("../providers/codex.mjs", import.meta.url), "utf8");
const codexProfiles = readFileSync(new URL("../codex-profiles.mjs", import.meta.url), "utf8");
const onboarding = readFileSync(new URL("../onboarding.mjs", import.meta.url), "utf8");
const sw = readFileSync(new URL("../public/sw.js", import.meta.url), "utf8");
const terminalHtml = readFileSync(new URL("../public/terminal.html", import.meta.url), "utf8");
const terminalJs = readFileSync(new URL("../public/terminal.js", import.meta.url), "utf8");

test("image references survive queue, steer, send, retry, and reload paths", () => {
  assert.match(html, /attachments: e\.attachments \?\? \[\]/);
  assert.match(html, /attachmentIds: \(entry\.attachments \?\? \[\]\)\.map/);
  assert.match(html, /attachmentIds: attachments\.map/);
  assert.match(html, /doSend\(entry\.text, \{ attachments: entry\.attachments/);
  assert.match(html, /state\.failedSends\.push\(\{ provider, threadId, text, requestId, attachments, retryWithNewId, errorMessage: cleanFailureReason\(errorMessage\), baseline, createdAt: Date\.now\(\) \}\)/);
  assert.match(html, /autoCheckStandaloneDelivery\(f, bubble, 250\)/);
  assert.match(html, /checkStandaloneDelivery\(failed, bubble, \{ announce = true \} = \{\}\)/);
  assert.doesNotMatch(html, /const freshNotFound = result\.state === "not_found"/);
  assert.match(html, /Steer delivery could not be confirmed/);
  assert.match(html, /retryWithNewId/);
  assert.match(html, /const attachments = imageParts\.map\(\(part\) => part\.attachment \?\? null\)/);
  assert.match(html, /button\.onclick = \(\) => viewAttachment\(attachment\)/);
  assert.match(html, /id="imageViewer"/);
  assert.match(html, /composerWrap\.addEventListener\("drop"/);
  assert.match(html, /event\.dataTransfer\?\.files/);
  assert.match(html, /const targetKey = localThreadKey\(target\)/);
  assert.match(html, /state\.active === target/);
  assert.match(html, /all\[targetKey\] = \{ \.\.\.saved, attachments: targetAttachments\.slice\(\), updatedAt: Date\.now\(\) \}/);
  assert.match(html, /Drop images to attach/);
  assert.match(html, /document\.addEventListener\("drop"/);
  assert.match(html, /id="resumeBtn"/);
  assert.match(html, /\/api\/resume/);
  assert.match(html, /button\.setAttribute\("aria-busy", "true"\)/);
  assert.match(html, /button\.textContent = "…"/);
  assert.match(html, /startSendProgress\(requestId, t\.id, "", null\)/);
  assert.match(server, /terminalOutcome === "aborted"/);
  assert.match(server, /\["stale_timeout", "historical_stale"\]\.includes\(runtime\.confidence\)/);
  assert.match(codexProvider, /input: resume \? \[\] : codexUserInput/);
  assert.match(html, /function syncComposerPrimaryAction\(\)/);
  assert.match(html, /state\.canResumeInterrupted && !state\.busy && !hasComposerContent/);
  assert.match(html, /sendActions"\)\.style\.display = showResume \? "none" : ""/);
  assert.match(codexProvider, /previousTurn\?\.status === "interrupted"/);
  assert.match(codexProvider, /isNativeUsageLimitTurn\(previousTurn\)/);
  assert.match(codexProvider, /bareTurnId\(previousTurn\?\.id\) === bareTurnId\(expectedPreviousTurnId\)/);
  assert.match(codexProvider, /result\?\.thread\?\.turns\?\.at\(-1\)/);
  assert.match(codexProvider, /reason: "resume-rejected"/);
});

test("failed delivery recovery distinguishes pre-dispatch failures and remains actionable", () => {
  assert.match(html, /messageAttempted = false/);
  assert.match(html, /const deliveryMayBeAmbiguous = messageAttempted/);
  assert.match(html, /const retryId = deliveryMayBeAmbiguous \? null : id/);
  assert.match(html, /\|\| e\.status >= 500/);
  assert.match(html, /responseInvalid/);
  assert.match(html, /\/api\/send\/status/);
  assert.match(html, /Not sent — Retry, Edit, or Cancel/);
  assert.match(html, /removePendingEntry\(entry, \{ allowUncertain: true \}\)/);
  assert.match(html, /if \(btn\.isConnected && btn\.disabled\)/);
  assert.match(html, /function markSendFailed\(bubble, onRetry, \{ uncertain = false, onDismiss = null, reason = null \} = \{\}\)/);
  assert.match(html, /detail\.className = "failed-reason"/);
  assert.match(html, /function cleanFailureReason\(value\)/);
  assert.match(html, /dismiss\.textContent = uncertain \? "Dismiss" : "Cancel"/);
  assert.match(html, /dropFailedSend\(f\.requestId\);\s*bubble\.remove\(\)/);
  assert.match(html, /dropFailedSend\(id\);\s*bubble\.remove\(\)/);
  assert.match(html, /result\.state === "failed"/);
  assert.doesNotMatch(html, /result\.state === "not_found" \|\| result\.state === "failed"/);
  assert.match(html, /legacyRetryWithNewId/);
  assert.match(html, /retryWithNewId = false/);
  assert.match(html, /this app will not resend it and risk a duplicate/);
  assert.match(html, /\/api\/send\/reconcile/);
  assert.match(html, /canonical\.state === "accepted"/);
  assert.match(html, /canonical\.state === "not_sent"/);
  assert.match(html, /\["turn_started", "provider_accepted"\]\.includes\(frame\.stage\)\) \{ confirmProviderAcceptedInUi\(frame\); \}/);
  assert.match(html, /if \(!frame\?\.requestId\) \{ return; \}/);
  assert.match(html, /finishSendProgress\(\);\s*dropFailedSend\(id\)/);
  assert.match(html, /function providerAcceptanceKey\(\{ provider, method, threadId, requestId \}\)/);
  assert.match(html, /if \(state\.providerAcceptedRequests\.has\(acceptanceKey\)\) \{/);
  assert.match(html, /if \(!state\.providerAcceptedRequests\.has\(acceptanceKey\)\) \{ advanceThreadUserProgress\(\); \}/);
  assert.match(html, /failed\.bubble = bubble;[\s\S]*?autoCheckStandaloneDelivery\(failed, bubble, 1200\)/);
  assert.match(html, /function restartAutomaticDeliveryChecks\(\)/);
  assert.match(html, /async function refreshAvailableProviders\(\)/);
  assert.match(html, /await api\("\/api\/providers"\)/);
  assert.match(html, /refreshAvailableProviders\(\)\.then/);
  assert.match(html, /probe\.runtime\?\.running && probe\.runtime\?\.source === "bridge"/);
  assert.match(html, /async function reconcileOpenRuntime\(thread = state\.active\)/);
  assert.match(html, /reconcileOpenRuntime\(state\.active\)\.then/);
  assert.match(html, /if \(runtime && !runtime\.running\) \{ resyncOpenThread\(\{ force: true \}\); \}/);
  assert.match(server, /baseline\.lastUserId/);
  assert.match(server, /userMessageText\(next\) === expected/);
  assert.match(server, /state: matched \? "accepted" : "superseded"/);
  assert.match(server, /expected\) \{ return \{ state: "unconfirmed"/);
  assert.match(claudeProvider, /code: "delivery_uncertain"/);
  assert.match(codexProvider, /p\.method === "turn\/start" \|\| p\.method === "turn\/steer"/);
  assert.match(codexProvider, /client\.pending\.set\(id, \{ resolve, reject, timer, method \}\)/);
  assert.match(html, /function canSteerPendingEntry\(entry\)/);
  assert.match(html, /entry\.nativeQueue\) \{ return false; \}/);
  assert.match(html, /state\.turnOwnership !== "bridge"/);
  assert.match(html, /steer\.textContent = activeProvider\(\) === "grok" \? "Interrupt & send now" : "Steer now"/);
  assert.match(html, /async function steerPendingEntry\(entry\)[\s\S]*?entry\.intendedSendMode = "steer"[\s\S]*?await trySteer\(entry\)/);
  assert.match(html, /for \(const entry of state\.pending\) \{ syncPendingActions\(entry\); \}/);
});

test("composer scratch text and saved prompt drafts are thread scoped", () => {
  assert.match(html, /const COMPOSER_DRAFTS_KEY = "cxp_composer_drafts"/);
  assert.match(html, /const SAVED_DRAFTS_KEY = "cxp_saved_drafts"/);
  assert.match(html, /function saveComposerDraft\(\)/);
  assert.match(html, /function restoreComposerDraft\(thread = state\.active\)/);
  assert.match(html, /async function openThread\(t\) \{\s*saveComposerDraft\(\);[\s\S]*?resetActivityGroup\(\)/);
  assert.match(html, /restoreComposerDraft\(t\)/);
  assert.match(html, /window\.addEventListener\("pagehide", saveComposerDraft\)/);
  assert.match(html, /id="draftStrip"/);
  assert.match(html, /id="steerAction">Steer/);
  assert.match(html, /id="queueAction">Queue/);
  assert.match(html, /id="saveDraftAction"/);
  assert.match(html, /openSendActionsMenu/);
  assert.match(html, /openControlPopover\(\$\("sendBtn"\)/);
  assert.match(html, /id="steerActionMobile"/);
  assert.match(html, /id="queueActionMobile"/);
  assert.match(html, /send\("steer"\)/);
  assert.match(html, /send\("queue"\)/);
  assert.match(html, /enqueue\(text, attachments, \{ intent: intent \?\? "queue" \}\)/);
  assert.match(html, /sendHoldTimer = setTimeout/);
  assert.match(html, /suppressSendClickUntil = Date\.now\(\) \+ 1000/);
  assert.match(html, /const canSend = hasMessage && !\$\('sendBtn'\)\.disabled/);
  assert.match(html, /\$\("sendActions"\)\.title = readiness\.ready/);
  assert.doesNotMatch(html, /id="draftBtn"/);
  assert.match(html, /Save current message as draft/);
  assert.match(html, /Queue all/);
  assert.match(html, /Steer all/);
  assert.match(html, /Delete all/);
  assert.match(html, /enqueue\(draft\.text \|\| "", draft\.attachments \?\? \[\], \{ intent \}\)/);
  assert.match(html, /entry\.deliveryPromise = trySteer\(entry\)/);
  assert.match(html, /for \(const draft of rows\) \{[\s\S]*?localThreadKey\(\) !== sheetThreadKey[\s\S]*?await dispatchSavedDraft\(draft, 'steer'\)/);
  assert.match(html, /\[COMPOSER_DRAFTS_KEY, SAVED_DRAFTS_KEY\]/);
  assert.match(html, /const baseline = raw\?\.baseline \?\? null/);
  assert.match(html, /existing\.baseline = baseline/);
  assert.match(html, /\["uncertain", "dispatching", "not_found"\]\.includes\(result\.state\)/);
  assert.match(html, /state\.threadUserProgress = res\.userProgress \?\? state\.threadUserProgress/);
  assert.match(html, /Could not save this draft on the device\. The composer was not cleared/);
});

test("image UI follows provider metadata and Grok cancel-before-send requires owned active work", () => {
  assert.match(html, /function supportsInput\(modality\)/);
  assert.match(html, /!supportsInput\("image"\)/);
  assert.match(html, /capabilitiesByProvider\.set\(provider, res\.capabilities/);
  assert.match(html, /requireActive: true/);
  assert.match(html, /Stopping Grok safely, then sending this message/);
});

test("stop, draft adoption, and reconnect preserve queue truth", () => {
  assert.match(html, /const stopped = await interruptApi\(\);[\s\S]*?if \(!stopped\) \{ return; \}[\s\S]*?await removePendingEntry\(p, \{ flush: false \}\)/);
  assert.match(html, /migrateThreadLocalState\(activeProvider\(\), state\.active\.id, params\.sessionId\)/);
  assert.match(html, /await api\("\/api\/message"[\s\S]*?finishSendProgress\(\);\s*dropFailedSend\(id\)/);
  assert.match(html, /Turn state could not be confirmed — this message remains unsent/);
  assert.match(html, /await reconcilePendingDeliveryProof\(\)/);
  assert.match(html, /entry\.deliveryProofChecked = true/);
  assert.match(html, /result\.state === "not_found"/);
  assert.match(html, /if \(entry\.deliveryProofChecked \|\| entry\.retryRequired \|\| entry\.mayHaveDispatched\) \{ continue; \}/);
  assert.match(html, /Delivery uncertain — check status or dismiss; this app will not resend it/);
  assert.match(html, /p\.bubble\?\.remove\(\)/);
  assert.match(html, /function openPendingEditSheet\(entry\)/);
  assert.match(html, /function removePendingEntry\(entry, \{ flush = true, allowUncertain = false \} = \{\}\)/);
  assert.match(html, /entry\.dispatching = true;\s*entry\.mayHaveDispatched = true;\s*syncPendingActions\(entry\);\s*savePending\(\)/);
  assert.match(html, /edit\.textContent = "Edit"/);
  assert.match(html, /cancel\.textContent = "Cancel"/);
  assert.match(html, /mayHaveDispatched: !!e\.mayHaveDispatched/);
  assert.match(html, /viaCodexQueue: !!e\.viaCodexQueue/);
  assert.match(html, /awaitingOwnership: !!e\.awaitingOwnership/);
  assert.match(html, /if \(entry\.mayHaveDispatched\) \{/);
  assert.match(html, /state\.pending\.includes\(entry\) \|\| entry\.dispatching \|\| entry\.mayHaveDispatched/);
  assert.match(html, /e\.code === "delivery_uncertain" \|\| !!e\.reach \|\| !!e\.responseInvalid \|\| !e\.status \|\| e\.status >= 500/);
  assert.match(html, /const external = res\.runtime\?\.source !== "bridge"/);
  assert.match(html, /state\.activeTurnId = external \? null : \(res\.runtime\?\.turnId \?\? state\.activeTurnId\)/);
  assert.match(html, /Queued in Codex — sends automatically when the current turn finishes/);
  assert.match(html, /persistExternalCodexQueue\(entry\)/);
  assert.match(html, /\/api\/queue\/update/);
  assert.match(html, /\/api\/queue\/delete/);
  assert.match(html, /state\.pending\.find\(\(entry\) => entry\.nativeQueue\)/);
  assert.match(html, /\/api\/thread\/runtime\?provider=codex/);
  assert.match(html, /Saved locally — waiting for ownership sync/);
  assert.match(server, /turnId: owned \? \(provider\.activeTurnId\?\.\(threadId\) \?\? null\) : null/);
  assert.match(server, /"POST \/api\/queue"/);
  assert.match(server, /"GET \/api\/thread\/runtime"/);
  assert.match(html, /setLockStatus\(\{ state: "unknown", label: "Check failed" \}\)/);
  assert.match(html, /refreshApprovals\(\);\s*refreshLockStatus\(\);/);
});

test("usage retry controls never present policy alone as a queued retry", () => {
  assert.match(html, /function usageRetryPolicyAppliesToOpenThread\(\)/);
  assert.doesNotMatch(html, /enabled \? "Auto-resume enabled"/);
  assert.match(html, /active \? "Resume queued" : alreadyResumed \? "Already resumed" : "Resume when usage returns"/);
  assert.match(html, /\["accepted", "cancelled", "superseded"\]/);
  assert.match(server, /usageRetryStore\.supersedeThread\(provider, threadId/);
  assert.match(server, /\["marker", "stalled"\]\.includes\(data\.runConfidence\)/);
  assert.match(html, /waiting_provider: "Auto-resume queued — provider temporarily unavailable"/);
  assert.match(server, /state: "waiting_provider"/);
  assert.match(server, /return exactThreadDispatch\(provider, entry\.threadId\)/);
});

test("Codex task settings expose a per-thread account without changing the global login", () => {
  assert.match(html, /Codex account for this task/);
  assert.match(html, /pins only this task; other Codex apps and tasks are unchanged/);
  assert.match(html, /data-codex-profile/);
  assert.match(html, /\/api\/codex\/thread-account/);
  assert.match(html, /The current turn will finish on its existing account/);
  assert.match(server, /provider\.modelsForThread\(body\.threadId\)/);
  assert.match(server, /provider\.usageForThread\(threadId/);
  assert.match(server, /"POST \/api\/codex\/thread-account"/);
  assert.match(codexProfiles, /CODEX_SQLITE_HOME/);
  assert.match(codexProvider, /accountRpcForThread/);
});

test("a forced reconnect verifies ownership before replaying a bridge-owned stream", () => {
  assert.match(html, /if \(state\.busy && !state\.externalTurn\) \{/);
  assert.match(html, /if \(!force\) \{ return; \}/);
  assert.match(html, /probe\.runtime\?\.running && probe\.runtime\?\.source === "bridge"/);
  assert.doesNotMatch(html, /state\.busy && !state\.externalTurn && \(!force \|\| state\.sendStage\)/);
});

test("task rows expose grouped subagents and device-scoped notification modes", () => {
  assert.match(html, /childCount} subagent/);
  assert.match(html, /document\.createElement\("button"\)/);
  assert.match(html, /name: child\.agentNickname \|\| child\.name \|\| "Subagent"/);
  assert.match(html, /parentThreadId: t\.id/);
  assert.match(html, /data-notify-mode="once"/);
  assert.match(html, /data-notify-mode="follow"/);
  assert.match(html, /Subagent work stays grouped/);
  assert.match(html, /\/api\/thread\/notifications/);
  const rowTemplate = html.slice(html.indexOf('div.innerHTML = `<div class="row-head"'), html.indexOf('div.querySelector(".preview")'));
  assert.ok(rowTemplate.indexOf("subagent-action") < rowTemplate.indexOf("notify-action"), "subagent disclosure stays left of the right-anchored notification action");
});

test("installed-app notification onboarding uses the real idempotent subscription path", () => {
  const start = html.indexOf("function wireNotificationOnboarding()");
  const end = html.indexOf("function clientId()", start);
  const flow = html.slice(start, end);
  assert.match(flow, /await ensurePushSubscription\(\)/);
  assert.doesNotMatch(flow, /enablePushSubscription/);
});

test("install onboarding cannot flash before standalone detection finishes", () => {
  const start = html.indexOf("function wireInstallOnboarding()");
  const end = html.indexOf("function wireNotificationOnboarding()", start);
  const flow = html.slice(start, end);
  assert.match(html, /#installOnboarding:not\(\.install-ready\) \{ display: none; \}/);
  assert.match(flow, /if \(isStandalone\(\).*hide\(\);\s*return;/s);
  assert.match(flow, /panel\.hidden = false;\s*panel\.classList\.add\("install-ready"\);/);
});

test("task list has orthogonal grouping and provider filters", () => {
  assert.match(html, /data-view="recent"/);
  assert.match(html, /data-view="projects"/);
  assert.match(html, /data-provider="all"/);
  assert.match(html, /aria-label="Codex"[^>]*><img/);
  assert.match(html, /\/api\/threads\/recent/);
  assert.match(html, /\/api\/threads\/projects/);
  assert.match(html, /listView === "recent"/);
  assert.match(html, /providerScope: "all"/);
  assert.match(html, /function rebuildProjectGroups\(\)/);
  assert.match(html, /className = "project-head"/);
  assert.match(html, /More sessions/);
  assert.match(html, /Load more sessions/);
  assert.doesNotMatch(html, /class="chip branch"/);
  assert.doesNotMatch(html, /querySelector\("\.branch"\)/);
  assert.match(html, /PROVIDER_ICONS/);
  assert.match(html, /providerMark\.setAttribute\("aria-label", providerName\)/);
  assert.match(html, /new-session-projects/);
  assert.match(html, /new-session-footer/);
  assert.match(html, /new-session-host/);
  assert.match(html, /Number\(b\.count \?\? 0\) - Number\(a\.count \?\? 0\)/);
  assert.match(html, /if \(providerChanged \|\| threadProvider === "codex"\)[\s\S]*?await initModels\(threadProvider, t\.id\);[\s\S]*?await loadThreadSettings\(t\)/);
  assert.match(html, /localStorage\.removeItem\("cxp_thread_prefs"\)/);
  assert.match(html, /\/api\/thread\/settings/);
  assert.match(html, /function updateListChrome\(\)[\s\S]*?button\.setAttribute\("aria-pressed", String\(selected\)\)[\s\S]*?if \(state\.active\) \{ return; \}/);
  assert.match(html, /button\.setAttribute\("aria-pressed", String\(selected\)\)/);
  assert.match(server, /nextState\[providerName\] = \{ unavailable: true \}/);
  assert.match(server, /recentProviderUnavailable\(cursorState\[name\]\)/);
  assert.match(html, /function syncProviderSeg\(\)[\s\S]*?button\.setAttribute\("aria-pressed", String\(selected\)\)/);
  assert.match(server, /extname\(iconName\).*"image\/svg\+xml"/);
});

test("live run-state transitions re-rank Recent Work and reconcile canonical state", () => {
  assert.match(html, /function rankLiveThreads\(threads, runningKeys\)/);
  assert.match(html, /const runningNow = isThreadRunning\(t\)/);
  assert.match(html, /if \(had !== on && live\)[\s\S]*?touchLiveThread\(provider, tid\)[\s\S]*?rerankVisibleRows\(\{ revealRunning: on \}\)[\s\S]*?scheduleListReconcile\(\)/);
  assert.match(html, /function rerankVisibleRows\(\{ revealRunning = false \} = \{\}\)[\s\S]*?state\.threads = rankLiveThreads\(state\.threads, state\.running\)[\s\S]*?revealRunning \? 0 : scrollTop/);
  assert.match(html, /if \(listView === "projects"\) \{ rebuildProjectGroups\(\); \}[\s\S]*?renderRows\(listView === "recent" && append\)/);
  assert.match(html, /const LIST_RECONCILE_MS = 600/);
  assert.match(html, /listReconcileTimer = setTimeout\([\s\S]*?loadThreads\(false\)\.catch/);
  assert.match(html, /markRunning\(threadProvider, t\.id, !!t\.running, \{ confidence: t\.runConfidence, live: false \}\)/);

  const notifyStart = html.indexOf("function onNotify(method, params, provider)");
  const notifyEnd = html.indexOf("// Once real turn output arrives", notifyStart);
  const notify = html.slice(notifyStart, notifyEnd);
  assert.ok(notify.indexOf('method === "turn/started"') < notify.indexOf("provider !== activeProvider()"), "cross-provider run state is recorded before transcript filtering");
});

test("quiet and vanished provider turns degrade visibly without unsafe queue dispatch", () => {
  assert.match(html, /confidence === "stalled"[\s\S]*?label: "no recent activity"/);
  assert.match(html, /confidence === "stale_timeout"[\s\S]*?label: "likely stopped"/);
  assert.match(html, /No provider activity was recorded for 10 minutes/);
  assert.match(html, /abnormalEnd[\s\S]*?setBusy\(false\)[\s\S]*?showTurnFailure/);
  assert.match(html, /requireActive: true/);
  assert.match(html, /updateRowRunning\(provider, tid, on, confidence\)/);
  assert.match(html, /No recent activity — the provider may be stalled/);
  assert.match(html, /showRuntimeRecovery[\s\S]*?bridge_restarted/);
});

test("usage sheet shows account limits for all providers and never thread usage", () => {
  assert.match(html, /data-usage-provider/);
  assert.match(html, /showUsageProvider\(button\.dataset\.usageProvider\)/);
  assert.match(html, /usageSheetCache = new Map\(\)/);
  assert.match(html, /\/api\/usage\?refresh=1&provider=/);
  assert.match(html, /\/api\/usage\/snapshot\?provider=/);
  assert.match(html, /cache: "no-store"/);
  assert.match(html, /refreshUsageProvider\(provider\)/);
  assert.match(html, /data-usage-refresh/);
  assert.match(html, /usage_refresh_timeout/);
  assert.match(html, /rateSource === "last-known" \|\| d\._meta\?\.refreshError/);
  assert.match(html, /function remainingPercentOf\(limit\)/);
  assert.match(html, /100 - used/);
  assert.match(html, /% left/);
  assert.match(html, /<h2>Usage remaining<\/h2>/);
  assert.doesNotMatch(html, /normalized across providers/);
  assert.match(html, /const limitsEnvelope = d\.rateLimits\?\.rateLimits/);
  assert.match(html, /Showing the last successful quota check/);
  assert.match(html, /Grok’s native billing endpoint/);
  assert.match(html, /esc\(String\(credits\.availableCount \?\? credits\.balance\)\)/);
  assert.match(html, /provider === lastUsageProvider/);
  assert.match(html, /dataset\.sheetKind === "usage"/);
  assert.match(server, /const USAGE_REFRESH_TIMEOUT_MS = 10000/);
  assert.match(server, /boundedUsageRefresh\(p\.usage\(\{ refresh:/);
  assert.match(server, /"GET \/api\/usage\/snapshot"/);
  assert.match(server, /fallback\._meta\.refreshError = true/);
  assert.doesNotMatch(html, /Latest local turn/);
  assert.doesNotMatch(html, /last input tokens/);
  assert.doesNotMatch(html, /Models used \(last turn\)/);
});

test("provider terminal errors stay visible live and after transcript reload", () => {
  assert.match(html, /case "turnError"/);
  assert.match(html, /showTurnFailure\(frame\.terminalError, frame\.terminalId\)/);
  assert.match(html, /showTurnFailure\(error \|\| "Turn failed", params\.turn\?\.id/);
  assert.match(html, /mcpServer\/startupStatus\/updated/);
  assert.match(html, /rateLimitReachedType/);
  assert.match(server, /terminalError, reply: reply \|\| terminalText/);
  assert.match(server, /const rawError = params\.error \?\? params\.turn\?\.error/);
  assert.match(server, /notificationBody\(reply, \{ failed, errorText: terminalError\?\.message \}\)/);
});

test("completed Claude text cannot overwrite a reasoning record with a colliding id", () => {
  assert.match(html, /kind: "agentMessage"/);
  assert.match(html, /kind: "reasoning"/);
  assert.match(html, /item\.type === "agentMessage" && rec\?\.kind === "agentMessage"/);
  assert.match(html, /item\.type === "reasoning" && rec\?\.kind === "reasoning"/);
});

test("desktop workspace keeps session navigation visible and constrains the chat", () => {
  assert.match(html, /@media \(min-width: 960px\)/);
  assert.match(html, /body\.thread-open #app[\s\S]*?grid-template-columns: clamp\(310px, 24vw, 380px\) minmax\(0, 1fr\)/);
  assert.match(html, /body\.thread-open #listView[\s\S]*?display: block !important/);
  assert.match(html, /body\.thread-open #transcript,[\s\S]*?width: min\(calc\(100% - 32px\), 70vw, 1100px\)/);
  assert.match(html, /body\.thread-open header \.htext[\s\S]*?left: clamp\(310px, 24vw, 380px\)[\s\S]*?right: 0[\s\S]*?text-align: center/);
  assert.match(html, /body\.thread-open\.sidebar-collapsed #app \{ grid-template-columns: 0 minmax\(0, 1fr\); \}/);
  assert.match(html, /body\.thread-open\.sidebar-collapsed #listView[\s\S]*?visibility: hidden/);
  assert.match(html, /id="sidebarToggleBtn"[\s\S]*?aria-expanded="true"/);
  assert.match(html, /function toggleSidebar\(forceExpanded = false\)/);
  assert.match(html, /sidebarCollapsed: state\.sidebarCollapsed/);
  assert.match(html, /border-left: 0;[\s\S]*?border-right: 0;/);
  assert.match(html, /body\.thread-open #backBtn \{ display: none !important; \}/);
  assert.match(html, /body\.thread-open #viewSeg,[\s\S]*?body\.thread-open #newBtn \{ display: flex !important; \}/);
  assert.match(html, /id="sidebarHead"[\s\S]*?id="viewSeg"[\s\S]*?id="providerSeg"/);
  assert.match(html, /id="searchRow"[\s\S]*?id="search"[\s\S]*?id="newBtn"/);
  assert.match(html, /id="newBtn"[^>]*aria-label="New chat"/);
  assert.match(html, /<aside id="listView" aria-label="Agent sessions">/);
  assert.match(html, /<main id="chatView" aria-label="Selected agent conversation">/);
  assert.match(html, /className = "row" \+ \(selected \? " active-thread" : ""\)/);
  assert.match(html, /aria-current="true"/);
  assert.match(html, /document\.body\.classList\.add\("thread-open"\)/);
  assert.match(html, /document\.body\.classList\.remove\("thread-open"\)/);
  assert.match(html, /event\.metaKey \|\| event\.ctrlKey/);
  assert.match(html, /event\.key === "Escape"/);
  assert.match(server, /const body = renderIndexHtml\(req\.headers\["user-agent"\][\s\S]*?return res\.end\(body\)/);
  assert.match(onboarding, /const readIndexShell = createIndexShellReader\(indexHtmlPath\)/);
  assert.match(sw, /const CACHE_VERSION = "remote-agents-v29"/);
});

test("rendered response links retain native browser link behavior outside Agents", () => {
  assert.match(html, /function decorateMarkdownLinks\(root\)/);
  assert.match(html, /if \(!href \|\| href\.startsWith\("#"\) \|\| localFileTarget\(href\)\) \{ continue; \}/);
  assert.match(html, /anchor\.target = "_blank";/);
  assert.match(html, /anchor\.rel = "noopener noreferrer";/);
  assert.match(html, /function renderFinalMarkdownInto\(el, text\) \{[\s\S]*?decorateMarkdownLinks\(el\);/);
  assert.match(html, /function appendAgent\(el, delta\) \{[\s\S]*?decorateMarkdownLinks\(el\);/);
  assert.match(html, /const markdown = el\.querySelector\("\.md\.filebody"\);[\s\S]*?decorateMarkdownLinks\(markdown\);/);
});

test("project terminal uses passkey step-up, a server-derived cwd, and an isolated interactive transport", () => {
  assert.match(html, /id="terminalBtn"[^>]*aria-label="Project terminal"/);
  assert.match(html, /function openNativeTerminal\(\)/);
  assert.match(html, /\/api\/terminal\/browser-handoff/);
  assert.match(terminalHtml, /simplewebauthn\.min\.js/);
  assert.match(terminalHtml, /xterm\.css/);
  assert.match(terminalJs, /startRegistration\(\{ optionsJSON: ceremony\.options \}\)/);
  assert.match(terminalJs, /startAuthentication\(\{ optionsJSON: ceremony\.options \}\)/);
  assert.match(terminalJs, /\/api\/terminal\/ticket/);
  assert.match(terminalJs, /new WebSocket/);
  assert.match(terminalJs, /const connection = new WebSocket/);
  assert.match(terminalJs, /if \(socket !== connection\) \{ return; \}/);
  assert.match(terminalJs, /command status may be uncertain/);
  assert.match(server, /"POST \/api\/terminal\/run"/);
  assert.match(server, /"GET \/api\/terminal\/status"/);
  assert.match(server, /"POST \/api\/terminal\/stop"/);
  assert.match(server, /resolveTerminalContext\(body\?\.provider, body\?\.threadId\)/);
  assert.match(server, /new WebSocketServer\(\{ noServer: true/);
  assert.match(server, /"\/terminal\.js": \{ file: "terminal\.js"/);
  assert.match(server, /"\/terminal\.css": \{ file: "terminal\.css"/);
  assert.match(server, /decodeURIComponent\(part\.slice\(index \+ 1\)\);[\s\S]*?catch \{[\s\S]*?return null;/);
  assert.match(server, /server\.on\("upgrade"[\s\S]*?try \{[\s\S]*?terminalWebSockets\.handleUpgrade[\s\S]*?catch \{/);
  assert.match(sw, /url\.pathname === "\/terminal"/);
});

test("usage-limit auto-resume is explicit, durable, cancellable, and defaults off", () => {
  assert.match(html, /id="settingsBtn"[^>]*aria-label="Task settings"/);
  assert.match(html, /Auto-resume after usage resets/);
  assert.match(html, /Enable for all chats/);
  assert.match(html, /Resume when usage returns/);
  assert.match(html, /api\("\/api\/usage-retries"/);
  assert.match(html, /api\("\/api\/usage-retries\/cancel"/);
  assert.match(html, /api\("\/api\/usage-retries\/check"/);
  assert.match(html, /function replaceThreadUsageRetries\([\s\S]*?state\.usageRetries\.delete/);
  assert.match(html, /renderHistory\(res\.thread, res\.itemWindow\);[\s\S]*?renderOpenUsageRetryState\(\)/);
  assert.match(html, /es\.addEventListener\("usage-retry"/);
  assert.match(server, /usage-retry-policy\.json/);
  assert.match(server, /setInterval\(\(\) => usageRetryRunner\.tick/);
  assert.match(server, /const \{ dispatch, progressGuard, \.\.\.publicEntry \} = entry/);
  assert.match(server, /_capacityFresh: live\?\._fresh\?\.rateLimits === true/);
  assert.match(html, /USAGE_LIMIT_CODES\.has\(code\)/);
  assert.match(html, /out\\s\+of\|no[\s\S]*credits\?/);
  assert.match(html, /decorateUsageLimitError\(el, item\)/);
  assert.match(html, /method === "account\/changing" \|\| method === "account\/changed"/);
  assert.match(html, /usageSheetCache\.delete\(provider\)/);
  assert.match(html, /refreshModelsAfterAccountChange\(provider\)/);
  assert.match(html, /const alreadyResumed = state\.busy && !active/);
  assert.match(html, /queueUsageResume\(error\?\.terminalId \|\| el\.dataset\.terminalId/);
  assert.match(server, /latestUnresolvedUsageStop\(full, provider\.name\)/);
  assert.match(server, /retry = await armLatestUsageResume\(body\.provider, body\.threadId\)/);
  assert.match(html, /if \(saved\.retry\) \{ updateUsageRetry\(saved\.retry\); \}/);
  assert.match(server, /code: "usage_already_resumed"/);
});

test("Codex write access stays provider-specific and retryable after a conflict", () => {
  assert.match(html, /const codexThread = state\.active && activeProvider\(\) === "codex" && !state\.active\.draft/);
  assert.match(html, /id="takeLockBtn">Try to get write access/);
  assert.match(html, /id="retryTakeLockBtn">Try again/);
  assert.match(html, /retryTakeLockBtn[\s\S]*?tryTakeLock/);
  assert.match(html, /function tryTakeLock\(btn\)[\s\S]*?\/api\/thread\/lock\/warm/);
  assert.match(html, /thread_locked_elsewhere[\s\S]*?renderLockSheet\(\)/);
  assert.match(html, /function openLockContent\(html\)[\s\S]*?openControlPopover\(\$\("lockCtl"\), html, "lock"\)/);
  assert.match(html, /function isLockSheetOpen\(\)[\s\S]*?dataset\.kind === "lock"/);
  assert.match(html, /setLockStatus\(next\);[\s\S]*?if \(isLockSheetOpen\(\)\) \{ renderLockSheet\(\); \}/);
  assert.doesNotMatch(html, />Warm up</);
});

test("composer settings fail closed and distinguish confirmed values from next-turn overrides", () => {
  assert.match(html, /id="settingsTruth" data-state="loading" role="status"/);
  assert.match(html, /function dispatchReadiness\(\)[\s\S]*?No exact model is selected/);
  assert.match(html, /settingsTruth\.state === "error"/);
  assert.match(html, /state\.modelsProvider !== activeProvider\(\)/);
  assert.match(html, /state\.modelsProvider !== \(t\.provider \|\| state\.provider\)/);
  assert.match(html, /function selectThreadSettingsPair\(settings, models, fallback\)/);
  assert.match(html, /const selection = selectThreadSettingsPair\(settings, state\.models/);
  assert.match(html, /saveThreadSettings\(recoverPair, \{ pending: false \}\)/);
  assert.match(html, /!materializedMode\.unknown && !materializedMode\.providerExact/);
  assert.match(html, /if \(selection\) \{[\s\S]*?syncControls\(\);[\s\S]*?if \(flush\) \{ flushPending\(\); \}/);
  assert.match(html, /id="modelEffortCtl" aria-label="Select model and reasoning effort"[^>]*><b id="modelName"/);
  assert.match(html, /id="composer"[\s\S]*?id="input"[\s\S]*?id="composerToolbar"[\s\S]*?id="controls"/);
  assert.match(html, /#composer \{ display: flex; flex-direction: column; gap: 8px/);
  assert.match(html, /#composerToolbar \{ display: flex; flex: 0 0 34px/);
  assert.match(html, /#input \{[\s\S]*?min-height: 42px[\s\S]*?padding: 4px 7px/);
  assert.doesNotMatch(html, /#composerToolbar \{ position: absolute/);
  assert.match(html, /#controls \{[\s\S]*?overflow-x: auto/);
  assert.match(html, /id="controlPopover" role="dialog" aria-modal="false"/);
  assert.match(html, /function openModelEffortSheet\(\)/);
  assert.match(html, /function openModelEffortSheet\(\)[\s\S]*?openControlPopover\(\$\("modelEffortCtl"\)/);
  assert.match(html, /function openModeSheet\(\)[\s\S]*?openControlPopover\(\$\("modeCtl"\)/);
  assert.match(html, /openModelSheet\(true\)/);
  assert.match(html, /openEffortSheet\(true\)/);
  assert.doesNotMatch(html, /id="steerCtl"|function openSendModeSheet\(\)/);
  assert.doesNotMatch(html, /id="modelCtl"|id="effortCtl"/);
  assert.doesNotMatch(html, /id="modelLabel"|id="effortLabel"/);
  assert.match(html, /Requested settings accepted by provider/);
  assert.match(html, /awaiting recorded confirmation/);
  assert.match(html, /const accepted = await api\("\/api\/message"/);
  assert.match(html, /const dispatch = \{[\s\S]*?model: state\.model,[\s\S]*?approvalPolicy: m\.approvalPolicy/);
  assert.match(html, /Current turn accepted · next override saved/);
  assert.match(html, /intent === "steer" && state\.turnOwnership === "bridge"/);
  assert.match(html, /Codex queue/);
  assert.match(html, /state\.uploadingAttachments > 0 \|\| !readiness\.ready/);
  assert.match(html, /Nothing was queued or sent/);
  assert.match(html, /providerExact/);
  assert.match(html, /role="dialog" aria-modal="true"/);
  assert.match(html, /aria-labelledby="sheetTitle" inert/);
  assert.match(html, /setAttribute\("inert", ""\)/);
  assert.match(html, />Provider-managed</);
  assert.match(html, /class="opt opt-button/);
  assert.match(html, /threadProvider !== state\.modelsProvider/);
  assert.match(html, /if \(!state\.active && name !== "all"\) \{ await initModels\(name\); \}/);
  assert.match(html, /function openUsageSheet\(\)[\s\S]*?const provider = activeProvider\(\)/);
  assert.match(server, /validateDispatchSettings\(provider\.name, body, listed, recorded, capabilities\)/);
  assert.match(server, /validateNewThreadModel\(p\.name, body\.model, listed\)/);
});
